/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/test.glb -o src/Avatar.jsx -r public 
*/

import React, { useEffect, useRef } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import * as THREE from 'three'
import { useEyeControllerWithMorphs, useFacialAnimation } from '../../utils/lipsyncAndExpression'
import { useConversation } from '../../contexts/ConversationContext'

export function Model({ ...props }) {
    const group = useRef<THREE.Group>(null)
    const { scene, animations } = useGLTF('/model/test.glb')
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
    const { nodes, materials } = useGraph(clone)
    const { actions } = useAnimations(animations, group)

    const { isSpeaking, facialExpression } = useConversation()

    useEffect(() => {
        console.log('is speaking: ', isSpeaking)
    }, [isSpeaking])

    useFacialAnimation(group, isSpeaking, facialExpression)
    useEyeControllerWithMorphs(group)
    useEffect(() => {
        if (animations.length > 0) {
            const firstClip = animations[3].name
            actions[firstClip]?.reset().fadeIn(0.5).play()
        }
    }, [])

    return (
        <group ref={group} {...props} dispose={null}>
            <group name='Scene'>
                <group name='Armature' scale={0.01}>
                    <primitive object={nodes.CC_Base_BoneRoot} />
                    <skinnedMesh
                        name='Bang'
                        geometry={nodes.Bang.geometry}
                        material={materials['Hair_Transparency.019']}
                        skeleton={nodes.Bang.skeleton}
                    />
                    <skinnedMesh
                        name='Bun'
                        geometry={nodes.Bun.geometry}
                        material={materials['Hair_Transparency.017']}
                        skeleton={nodes.Bun.skeleton}
                    />
                    <group name='Hair_Base'>
                        <skinnedMesh
                            name='Hair_Base004'
                            geometry={nodes.Hair_Base004.geometry}
                            material={materials['Hair_Transparency.016']}
                            skeleton={nodes.Hair_Base004.skeleton}
                        />
                        <skinnedMesh
                            name='Hair_Base004_1'
                            geometry={nodes.Hair_Base004_1.geometry}
                            material={materials['Scalp_Transparency.004']}
                            skeleton={nodes.Hair_Base004_1.skeleton}
                        />
                    </group>
                    <skinnedMesh
                        name='Knee_length_skirt'
                        geometry={nodes.Knee_length_skirt.geometry}
                        material={materials['Knee_length_skirt.003']}
                        skeleton={nodes.Knee_length_skirt.skeleton}
                    />
                    <skinnedMesh
                        name='Real_Hair'
                        geometry={nodes.Real_Hair.geometry}
                        material={materials['Hair_Transparency.018']}
                        skeleton={nodes.Real_Hair.skeleton}
                    />
                    <skinnedMesh
                        name='Rolled_sleeves_shirt'
                        geometry={nodes.Rolled_sleeves_shirt.geometry}
                        material={materials['Rolled_sleeves_shirt.003']}
                        skeleton={nodes.Rolled_sleeves_shirt.skeleton}
                    />
                    <group name='CC_Base_Body'>
                        <skinnedMesh
                            name='CC_Base_Body004'
                            geometry={nodes.CC_Base_Body004.geometry}
                            material={materials['Std_Skin_Head.004']}
                            skeleton={nodes.CC_Base_Body004.skeleton}
                            morphTargetDictionary={nodes.CC_Base_Body004.morphTargetDictionary}
                            morphTargetInfluences={nodes.CC_Base_Body004.morphTargetInfluences}
                        />
                        <skinnedMesh
                            name='CC_Base_Body004_1'
                            geometry={nodes.CC_Base_Body004_1.geometry}
                            material={materials['Std_Skin_Body.004']}
                            skeleton={nodes.CC_Base_Body004_1.skeleton}
                            morphTargetDictionary={nodes.CC_Base_Body004_1.morphTargetDictionary}
                            morphTargetInfluences={nodes.CC_Base_Body004_1.morphTargetInfluences}
                        />
                        <skinnedMesh
                            name='CC_Base_Body004_2'
                            geometry={nodes.CC_Base_Body004_2.geometry}
                            material={materials['Std_Skin_Arm.004']}
                            skeleton={nodes.CC_Base_Body004_2.skeleton}
                            morphTargetDictionary={nodes.CC_Base_Body004_2.morphTargetDictionary}
                            morphTargetInfluences={nodes.CC_Base_Body004_2.morphTargetInfluences}
                        />
                        <skinnedMesh
                            name='CC_Base_Body004_3'
                            geometry={nodes.CC_Base_Body004_3.geometry}
                            material={materials['Std_Skin_Leg.004']}
                            skeleton={nodes.CC_Base_Body004_3.skeleton}
                            morphTargetDictionary={nodes.CC_Base_Body004_3.morphTargetDictionary}
                            morphTargetInfluences={nodes.CC_Base_Body004_3.morphTargetInfluences}
                        />
                        <skinnedMesh
                            name='CC_Base_Body004_4'
                            geometry={nodes.CC_Base_Body004_4.geometry}
                            material={materials['Std_Nails.004']}
                            skeleton={nodes.CC_Base_Body004_4.skeleton}
                            morphTargetDictionary={nodes.CC_Base_Body004_4.morphTargetDictionary}
                            morphTargetInfluences={nodes.CC_Base_Body004_4.morphTargetInfluences}
                        />
                        <skinnedMesh
                            name='CC_Base_Body004_5'
                            geometry={nodes.CC_Base_Body004_5.geometry}
                            material={materials['Std_Eyelash.004']}
                            skeleton={nodes.CC_Base_Body004_5.skeleton}
                            morphTargetDictionary={nodes.CC_Base_Body004_5.morphTargetDictionary}
                            morphTargetInfluences={nodes.CC_Base_Body004_5.morphTargetInfluences}
                        />
                    </group>
                    <group name='CC_Base_Eye'>
                        <skinnedMesh
                            name='CC_Base_Eye001'
                            geometry={nodes.CC_Base_Eye001.geometry}
                            material={materials['Std_Eye_R.004']}
                            skeleton={nodes.CC_Base_Eye001.skeleton}
                            morphTargetDictionary={nodes.CC_Base_Eye001.morphTargetDictionary}
                            morphTargetInfluences={nodes.CC_Base_Eye001.morphTargetInfluences}
                        />
                        <skinnedMesh
                            name='CC_Base_Eye001_1'
                            geometry={nodes.CC_Base_Eye001_1.geometry}
                            material={materials['Std_Cornea_R.004']}
                            skeleton={nodes.CC_Base_Eye001_1.skeleton}
                            morphTargetDictionary={nodes.CC_Base_Eye001_1.morphTargetDictionary}
                            morphTargetInfluences={nodes.CC_Base_Eye001_1.morphTargetInfluences}
                        />
                        <skinnedMesh
                            name='CC_Base_Eye001_2'
                            geometry={nodes.CC_Base_Eye001_2.geometry}
                            material={materials['Std_Eye_L.004']}
                            skeleton={nodes.CC_Base_Eye001_2.skeleton}
                            morphTargetDictionary={nodes.CC_Base_Eye001_2.morphTargetDictionary}
                            morphTargetInfluences={nodes.CC_Base_Eye001_2.morphTargetInfluences}
                        />
                        <skinnedMesh
                            name='CC_Base_Eye001_3'
                            geometry={nodes.CC_Base_Eye001_3.geometry}
                            material={materials['Std_Cornea_L.004']}
                            skeleton={nodes.CC_Base_Eye001_3.skeleton}
                            morphTargetDictionary={nodes.CC_Base_Eye001_3.morphTargetDictionary}
                            morphTargetInfluences={nodes.CC_Base_Eye001_3.morphTargetInfluences}
                        />
                    </group>
                    <group name='CC_Base_EyeOcclusion'>
                        <skinnedMesh
                            name='CC_Base_EyeOcclusion004'
                            geometry={nodes.CC_Base_EyeOcclusion004.geometry}
                            material={materials['Std_Eye_Occlusion_R.004']}
                            skeleton={nodes.CC_Base_EyeOcclusion004.skeleton}
                            morphTargetDictionary={nodes.CC_Base_EyeOcclusion004.morphTargetDictionary}
                            morphTargetInfluences={nodes.CC_Base_EyeOcclusion004.morphTargetInfluences}
                        />
                        <skinnedMesh
                            name='CC_Base_EyeOcclusion004_1'
                            geometry={nodes.CC_Base_EyeOcclusion004_1.geometry}
                            material={materials['Std_Eye_Occlusion_L.004']}
                            skeleton={nodes.CC_Base_EyeOcclusion004_1.skeleton}
                            morphTargetDictionary={nodes.CC_Base_EyeOcclusion004_1.morphTargetDictionary}
                            morphTargetInfluences={nodes.CC_Base_EyeOcclusion004_1.morphTargetInfluences}
                        />
                    </group>
                    <group name='CC_Base_TearLine'>
                        <skinnedMesh
                            name='CC_Base_TearLine004'
                            geometry={nodes.CC_Base_TearLine004.geometry}
                            material={materials['Std_Tearline_R.004']}
                            skeleton={nodes.CC_Base_TearLine004.skeleton}
                            morphTargetDictionary={nodes.CC_Base_TearLine004.morphTargetDictionary}
                            morphTargetInfluences={nodes.CC_Base_TearLine004.morphTargetInfluences}
                        />
                        <skinnedMesh
                            name='CC_Base_TearLine004_1'
                            geometry={nodes.CC_Base_TearLine004_1.geometry}
                            material={materials['Std_Tearline_L.004']}
                            skeleton={nodes.CC_Base_TearLine004_1.skeleton}
                            morphTargetDictionary={nodes.CC_Base_TearLine004_1.morphTargetDictionary}
                            morphTargetInfluences={nodes.CC_Base_TearLine004_1.morphTargetInfluences}
                        />
                    </group>
                    <group name='CC_Base_Teeth'>
                        <skinnedMesh
                            name='CC_Base_Teeth001'
                            geometry={nodes.CC_Base_Teeth001.geometry}
                            material={materials['Std_Upper_Teeth.004']}
                            skeleton={nodes.CC_Base_Teeth001.skeleton}
                            morphTargetDictionary={nodes.CC_Base_Teeth001.morphTargetDictionary}
                            morphTargetInfluences={nodes.CC_Base_Teeth001.morphTargetInfluences}
                        />
                        <skinnedMesh
                            name='CC_Base_Teeth001_1'
                            geometry={nodes.CC_Base_Teeth001_1.geometry}
                            material={materials['Std_Lower_Teeth.004']}
                            skeleton={nodes.CC_Base_Teeth001_1.skeleton}
                            morphTargetDictionary={nodes.CC_Base_Teeth001_1.morphTargetDictionary}
                            morphTargetInfluences={nodes.CC_Base_Teeth001_1.morphTargetInfluences}
                        />
                    </group>
                    <skinnedMesh
                        name='CC_Base_Tongue'
                        geometry={nodes.CC_Base_Tongue.geometry}
                        material={materials['Std_Tongue.004']}
                        skeleton={nodes.CC_Base_Tongue.skeleton}
                        morphTargetDictionary={nodes.CC_Base_Tongue.morphTargetDictionary}
                        morphTargetInfluences={nodes.CC_Base_Tongue.morphTargetInfluences}
                    />
                    <group name='Female_Angled'>
                        <skinnedMesh
                            name='Female_Angled004'
                            geometry={nodes.Female_Angled004.geometry}
                            material={materials['Female_Angled_Transparency.004']}
                            skeleton={nodes.Female_Angled004.skeleton}
                            morphTargetDictionary={nodes.Female_Angled004.morphTargetDictionary}
                            morphTargetInfluences={nodes.Female_Angled004.morphTargetInfluences}
                        />
                        <skinnedMesh
                            name='Female_Angled004_1'
                            geometry={nodes.Female_Angled004_1.geometry}
                            material={materials['Female_Angled_Base_Transparency.004']}
                            skeleton={nodes.Female_Angled004_1.skeleton}
                            morphTargetDictionary={nodes.Female_Angled004_1.morphTargetDictionary}
                            morphTargetInfluences={nodes.Female_Angled004_1.morphTargetInfluences}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/model/test.glb')
